%-------------------------------------------------------------------------------
% An example report
%
% Modify the (re-usable) title page layout and structure in global/frontmatter.Rnw
% Define the report-specific content in variables below.
% IMPORTANT set work dir to the location of this file, e.g.:
% setwd("~/projects/datawagovau/ckan-o-sweave/reports")
%-------------------------------------------------------------------------------
\input{global/header}
\begin{document}
\SweaveOpts{concordance=TRUE, echo=FALSE}
<<echo=FALSE>>=
source('../scripts/ckan_secret.R')
source('../scripts/ckan.R')
mpa_name <- "The report title"
report_slug <- "example1"
mpa_period <- "2014-2015"
mpa_year <- "2015"
mpa_editor <- "John Doe, Jane Doette"
mpa_editor_reverse <- "Doe J, Doette J"
mpa_contributors <- paste0("John Johnson, Steven Stevenson")
mpa_contributors_reverse <- paste0("Johnson J, Stevenson S")
mpa_wammp <- "data.wa.gov.au"
mpa_report_title <- "An example report title"
mpa_mmu <- "The data.wa.gov.au initiative of Western Australia"
mpa_mmu_msp <- "Address line 1"
mpa_mmu_address <- "Address line 2"
img <- ckan_res("7a19940b-6697-4fe8-a03e-60c99bb606a6")
@
\SweaveInput{global/frontmatter.Rnw}
%-------------------------------------------------------------------------------
% Chapters: create in parts/
%-------------------------------------------------------------------------------
\SweaveInput{parts/chapter1.Rnw}
\SweaveInput{global/backmatter.Rnw}
\end{document}
% EOF --------------------------------------------------------------------------
