% !Rnw root = ../report01.Rnw
% %----------------------------------------------------------------------------------------
% %  BIBLIOGRAPHY
% %----------------------------------------------------------------------------------------
% \chapterimage{img/fsh}
% \chapter*{Bibliography}
% \addcontentsline{toc}{chapter}{\textcolor{ocre}{Bibliography}}
% \section*{Books}
% %\addcontentsline{toc}{section}{Books}
% \printbibliography[heading=bibempty,type=book]
% \section*{Articles}
% %\addcontentsline{toc}{section}{Articles}
% \printbibliography[heading=bibempty,type=article]

%----------------------------------------------------------------------------------------
%	INDEX
%----------------------------------------------------------------------------------------

\cleardoublepage
\phantomsection
\setlength{\columnsep}{0.75cm}
\addcontentsline{toc}{chapter}{\textcolor{ocre}{Index}}
\printindex

%----------------------------------------------------------------------------------------

%----------------------------------------------------------------------------------------
%  Appendix
%----------------------------------------------------------------------------------------
\thispagestyle{empty}
<<echo=FALSE>>=
i <-ckan_res("7a19940b-6697-4fe8-a03e-60c99bb606a6")
@
\write18{wget -x \Sexpr{i$url}}
\chapterimage{\Sexpr{i$pth}}
\chapter*{Appendix 1 - Authors' Workflow}
\label{sec:report-workflow}
\addcontentsline{toc}{chapter}{\textcolor{ocre}{Appendix 1 - Authors' Workflow}}
\input{global/workflow}

\thispagestyle{empty}
<<echo=FALSE>>=
i <- ckan_res("7a19940b-6697-4fe8-a03e-60c99bb606a6")
@
\write18{wget -x \Sexpr{i$url}}
\chapterimage{\Sexpr{i$pth}}
\chapter*{Appendix 2 - Authors' Manual}
\label{sec:report-manual}
\addcontentsline{toc}{chapter}{\textcolor{ocre}{Appendix 2 - Authors' Manual}}
\input{global/manual}
